type: 'cifar10'
in_shape: [3, 32, 32]
output_size: 10
num_tasks: ${num_tasks}
input_data_ratios: ${input_data_ratios}
label_noise_ratios: ${label_noise_ratios}
buffer_size: 50000

train:
  root: '/home/hojoonlee/assets/CIFAR10/train' 
  transforms:
    crop_type: 'none' # [none, center, random_resize, random_pad]
    scale: null
    crop_size: null   
    pad_size: null
    horizontal_flip: false
    gray_scale: false
    normalize:
      mean: [0.4914, 0.4822, 0.4465] 
      std: [0.2023, 0.1994, 0.2010] # https://github.com/kuangliu/pytorch-cifar/blob/master/main.py 
  shuffle: true

test:
  root: '/home/hojoonlee/assets/CIFAR10/val' 
  transforms:
    crop_type: 'none' # [center, random, none]
    scale: null
    crop_size: null
    pad_size: null
    horizontal_flip: false
    gray_scale: false
    normalize:
      mean: [0.4914, 0.4822, 0.4465] 
      std: [0.2023, 0.1994, 0.2010]
  shuffle: false

dataloader:
  batch_size: 256
  num_workers: 4
  pin_memory: true