type: 'cifar100'
in_shape: [3, 32, 32]
output_size: 100
num_tasks: ${num_tasks}
input_data_ratios: ${input_data_ratios}
label_noise_ratios: ${label_noise_ratios}
buffer_size: 50000

train:
  root: '/home/hojoonlee/assets/CIFAR100/train' 
  transforms:
    crop_type: 'none' # [none, center, random_resize, random_pad]
    scale: null
    crop_size: null   
    pad_size: null
    horizontal_flip: false
    gray_scale: false
    normalize:
      mean: [0.5070751592371323, 0.48654887331495095, 0.4409178433670343] 
      std: [0.2673342858792401, 0.2564384629170883, 0.27615047132568404] # https://github.com/weiaicunzai/pytorch-cifar100/blob/master/conf/global_settings.py
  shuffle: true

test:
  root: '/home/hojoonlee/assets/CIFAR100/val' 
  transforms:
    crop_type: 'none' # [center, random, none]
    scale: null
    crop_size: null
    pad_size: null
    horizontal_flip: false
    gray_scale: false
    normalize:
      mean: [0.5088964127604166, 0.48739301317401956, 0.44194221124387256] 
      std: [0.2682515741720801, 0.2573637364478126, 0.2770957707973042]
  shuffle: false

dataloader:
  batch_size: 256 # 256
  num_workers: 4
  pin_memory: true