project_name: 'plasticity'
group_name: 'test'
exp_name: 'test'
device: 'cuda:0'
seed: 0

num_tasks: 10
input_data_ratios:  [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
label_noise_ratios: [0.5, 0.4, 0.4, 0.3, 0.3, 0.2, 0.2, 0.1, 0.1, 0.0]

defaults:
- _self_