trainer:
  optimizer:
    lr: 0.001
    weight_decay: 0.001
  base_epochs: 10
  base_test_every: 2

dataset:
  train:
    transforms:
      crop_type: 'random_pad'
      crop_size: 32   
      pad_size: 4
      horizontal_flip: true

defaults:
- _continual
- dataset: cifar10
- model: resnet18_gap
- trainer: base
- _self_