trainer:
  optimizer:
    lr: 0.003
    weight_decay: 0.05
  base_epochs: 10
  base_test_every: 2

dataset:
  train:
    transforms:
      crop_type: 'random_pad'
      crop_size: 32   
      pad_size: 4
      horizontal_flip: true

defaults:
- _continual
- dataset: cifar100
- model: vit-ti_linear
- trainer: base
- _self_